kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: regional-pd
provisioner: kubernetes.io/gce-pd
parameters:
  type: pd-standard
  replication-type: regional-pd
  zones: asia-northeast1-a, asia-northeast1-b, asia-northeast1-c
