apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ${SERVICE}-pvc-assets-${DEPLOY_REV}
  namespace: ${NAMESPACE}
spec:
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: regional-pd
